# Site
name: 'Ayodhya Live'
description: 'Special information about the birthplace of Lord Shri Ram so far.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
disqus: 'ayodhyalive'
email: 'ayodhyalive@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    ayodhyalive:
      name:           Ayodhyalive
      site:           https://www.ayodhyalive.com
      avatar:         assets/images/avatar1.png
      bio:            "Hi, I am Ayodhyalive, the author of Portal, the theme you're currently previewing. I hope you like it!"
      email:          ayodhyalive@gmail.com
      twitter:        https://twitter.com/ayodhyalive
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ayodhyalive
      avatar: assets/images/avatar1.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
