backend:
  name: git-gateway
  branch: master
  repo: earthcorp/mundana-theme-jekyll
  identity_url: "https://www.ayodhyalive.com/.netlify/identity"
  gateway_url: "https://www.ayodhyalive.com/.netlify/git"
  squash_merges: true
  
publish_mode: editorial_workflow
media_folder: "/images/uploads"

site_url: https://ayodhyalive.com
logo_url: https://ayodhyalive.com/assets/images/logo.png
  
collections:
  - label: "Sitewide Options"
    name: options
    editor:
      preview: false
    files:
      - label: "Navigation Menu"
        name: nav
        file: "_data/nav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - {label: "Display Text", name: displayText, widget: string}
              - {label: URL, name: url, widget: string}
              - label: "Item Type"
                name: itemType
                widget: select
                options: ["Link", "Button"]
