backend:
  name: git-gateway
  branch: master
  repo: earthcorp/mundana-theme-jekyll
  identity_url: "https://www.ayodhyalive.com/.netlify/identity"
  gateway_url: "https://www.ayodhyalive.com/.netlify/git"
  squash_merges: true
  
publish_mode: editorial_workflow
media_folder: "/images/uploads"

site_url: https://ayodhyalive.com
logo_url: https://ayodhyalive.com/assets/images/logo.png
  
collections:                
   - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Category", name: "category", widget: "string", default: "jekyll"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
 
