backend:
  name: git-gateway
  branch: master
  repo: earthcorp/mundana-theme-jekyll
media_folder: "assets/images"
public_folder: "images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Categories", name: "categories", widget: "string", required: false}
      - { label: "Meta image", name: "image", widget: "image", required: false}
      - { label: "Post Body", name: "body", widget: "markdown" } 
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie
    label_singular: "Page" # Used in the UI, ie.: "New Post"
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Featured image", name: "feature_image", widget: "image", required: false}
      - {label: "Feature text", name: "feature_text", widget: "markdown", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Meta image", name: "image", widget: "image", required: false}
